services:
  web:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    ports:
      - "8001:8001"
    command: sh -c "python manage.py migrate && daphne wedding_res.asgi:application -b 0.0.0.0 -p 8001"
    depends_on:
      - db

  db:
    build: ./docker/postgres
    ports:
      - "5433:5432"
    volumes:
      - wedding_res_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}

  redis:
    image: redis:6
    ports:
      - "6380:6379"

  celery_worker:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: celery -A wedding_res worker --loglevel=info
    depends_on:
      - db
      - redis

  celery_beat:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env
    command: celery -A wedding_res beat --loglevel=info
    depends_on:
      - db
      - redis
      
volumes:
  wedding_res_postgres_data: