# Generated by Django 5.2.4 on 2025-07-20 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weddingevent',
            options={},
        ),
        migrations.RemoveField(
            model_name='weddingevent',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='weddingevent',
            name='max_guests',
        ),
        migrations.RemoveField(
            model_name='weddingevent',
            name='slug',
        ),
        migrations.AddField(
            model_name='weddingevent',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='weddingevent',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='weddingevent',
            name='venue',
            field=models.CharField(max_length=255),
        ),
    ]
