# Generated by Django 5.2.4 on 2025-07-21 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0002_alter_weddingevent_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='card_image',
            field=models.ImageField(blank=True, null=True, upload_to='guest_cards/'),
        ),
    ]
