# Generated by Django 5.2.4 on 2025-08-14 14:39

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_guest_guest_name_alter_guest_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='payment_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Registration fee for this guest', max_digits=10, null=True),
        ),
        migrations.CreateModel(
            name='EventSchedule',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_name', models.CharField(help_text='e.g., Ceremony, Reception, After Party', max_length=255)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1, help_text='Order of events (1, 2, 3, etc.)')),
                ('wedding_event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_schedules', to='cards.weddingevent')),
            ],
            options={
                'verbose_name': 'Event Schedule',
                'verbose_name_plural': 'Event Schedules',
                'ordering': ['order', 'date'],
            },
        ),
    ]
