# Generated by Django 5.2.4 on 2025-07-21 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0003_guest_card_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='weddingevent',
            name='couple',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
