# Generated by Django 5.2.4 on 2025-07-22 08:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0004_weddingevent_couple'),
    ]

    operations = [
        migrations.AddField(
            model_name='guest',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes/'),
        ),
    ]
