# Generated by Django 5.2.4 on 2025-07-23 12:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0005_guest_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitation',
            name='card_image',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='qr_code',
        ),
        migrations.RemoveField(
            model_name='qrverification',
            name='invitation',
        ),
        migrations.RemoveField(
            model_name='qrverification',
            name='scanned_by',
        ),
        migrations.AddField(
            model_name='qrverification',
            name='guest',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='cards.guest'),
        ),
        migrations.AlterField(
            model_name='qrverification',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddConstraint(
            model_name='qrverification',
            constraint=models.UniqueConstraint(fields=('guest',), name='unique_qrverification_guest'),
        ),
    ]
