# Generated by Django 5.2.4 on 2025-07-24 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0006_remove_invitation_card_image_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='weddingevent',
            options={'ordering': ['-date']},
        ),
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together={('invitation',)},
        ),
        migrations.AlterField(
            model_name='guest',
            name='is_attending',
            field=models.BooleanField(default=True),
        ),
    ]
