# Generated by Django 5.2.4 on 2025-07-24 07:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0007_alter_weddingevent_options_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='guest',
            unique_together=set(),
        ),
    ]
