# Generated by Django 5.2.4 on 2025-07-24 07:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0008_alter_guest_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrverification',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
